[package]
name = "unit-converter-parser"
version = "0.1.0"
edition = "2021"
description = "A unit conversion parser using Rust and Pest for syntax parsing."
license = "MIT"
readme = "README.md"

[dependencies]
pest = "2.7.14"
pest_derive = "2.7.14"
anyhow = "1.0.93"
thiserror = "2.0.0"